### PR TITLE
make package routines virtual

### PR DESCRIPTION
**Pull request by gonuke**
Make packaging apply across all resources

### CODE REVIEW

**Comment by nuclearkatie** [comment]
Does this get cycamore to build on your machine? It doesn't for mine...

**Comment by gonuke** [comment]
I think you might need a rebase to make the conda tests pass here (#1696) based on something that emerged yesterday.

I haven't tried cycamore with this... let me give it a shot see how to fix it.  Do you have the cycamore error?

**Comment by nuclearkatie** [comment]
```
/home/nuclearkatie/.local/include/cyclus/toolkit/res_buf.h: In instantiation of ‘void cyclus::toolkit::ResBuf<T>::Push(std::vector<B>) [with B = boost::shared_ptr<cyclus::Resource>; T = cyclus::Resource]’:
/home/nuclearkatie/cyclus/cycamore/src/sink.cc:32:35:   required from here
/home/nuclearkatie/.local/include/cyclus/toolkit/res_buf.h:331:9: error: no matching function for call to ‘cyclus::Resource::ChangePackageId()’
  331 |         rss[i]->ChangePackageId();
      |         ^~~
In file included from /home/nuclearkatie/.local/include/cyclus/agent.h:15,
                 from /home/nuclearkatie/.local/include/cyclus/context.h:17,
                 from /home/nuclearkatie/.local/include/cyclus/cyclus.h:11,
                 from /home/nuclearkatie/cyclus/cycamore/src/sink.h:9,
                 from /home/nuclearkatie/cyclus/cycamore/src/sink.cc:7:
/home/nuclearkatie/.local/include/cyclus/resource.h:98:16: note: candidate: ‘virtual void cyclus::Resource::ChangePackageId(int)’
   98 |   virtual void ChangePackageId(int new_package_id) = 0;
      |                ^~~~~~~~~~~~~~~
/home/nuclearkatie/.local/include/cyclus/resource.h:98:16: note:   candidate expects 1 argument, 0 provided
In file included from /home/nuclearkatie/.local/include/cyclus/toolkit/matl_buy_policy.h:9,
                 from /home/nuclearkatie/.local/include/cyclus/cyclus.h:51,
                 from /home/nuclearkatie/cyclus/cycamore/src/sink.h:9,
                 from /home/nuclearkatie/cyclus/cycamore/src/sink.cc:7:
/home/nuclearkatie/.local/include/cyclus/toolkit/res_buf.h:335:9: error: no matching function for call to ‘cyclus::Resource::ChangePackageId()’
  335 |         rss[i]->ChangePackageId();
      |         ^~~
In file included from /home/nuclearkatie/.local/include/cyclus/agent.h:15,
                 from /home/nuclearkatie/.local/include/cyclus/context.h:17,
                 from /home/nuclearkatie/.local/include/cyclus/cyclus.h:11,
                 from /home/nuclearkatie/cyclus/cycamore/src/sink.h:9,
                 from /home/nuclearkatie/cyclus/cycamore/src/sink.cc:7:
/home/nuclearkatie/.local/include/cyclus/resource.h:98:16: note: candidate: ‘virtual void cyclus::Resource::ChangePackageId(int)’
   98 |   virtual void ChangePackageId(int new_package_id) = 0;
      |                ^~~~~~~~~~~~~~~
/home/nuclearkatie/.local/include/cyclus/resource.h:98:16: note:   candidate expects 1 argument, 0 provided
In file included from /home/nuclearkatie/.local/include/cyclus/toolkit/matl_buy_policy.h:9,
                 from /home/nuclearkatie/.local/include/cyclus/cyclus.h:51,
                 from /home/nuclearkatie/cyclus/cycamore/src/sink.h:9,
                 from /home/nuclearkatie/cyclus/cycamore/src/sink.cc:7:
/home/nuclearkatie/.local/include/cyclus/toolkit/res_buf.h: In instantiation of ‘void cyclus::toolkit::ResBuf<T>::Push(cyclus::Resource::Ptr) [with T = cyclus::Resource; cyclus::Resource::Ptr = boost::shared_ptr<cyclus::Resource>]’:
/home/nuclearkatie/cyclus/cycamore/src/sink.cc:167:30:   required from here
/home/nuclearkatie/.local/include/cyclus/toolkit/res_buf.h:278:7: error: no matching function for call to ‘cyclus::Resource::ChangePackageId()’
  278 |       m->ChangePackageId();
      |       ^
In file included from /home/nuclearkatie/.local/include/cyclus/agent.h:15,
                 from /home/nuclearkatie/.local/include/cyclus/context.h:17,
                 from /home/nuclearkatie/.local/include/cyclus/cyclus.h:11,
                 from /home/nuclearkatie/cyclus/cycamore/src/sink.h:9,
                 from /home/nuclearkatie/cyclus/cycamore/src/sink.cc:7:
/home/nuclearkatie/.local/include/cyclus/resource.h:98:16: note: candidate: ‘virtual void cyclus::Resource::ChangePackageId(int)’
   98 |   virtual void ChangePackageId(int new_package_id) = 0;
      |                ^~~~~~~~~~~~~~~
/home/nuclearkatie/.local/include/cyclus/resource.h:98:16: note:   candidate expects 1 argument, 0 provided
In file included from /home/nuclearkatie/.local/include/cyclus/toolkit/matl_buy_policy.h:9,
                 from /home/nuclearkatie/.local/include/cyclus/cyclus.h:51,
                 from /home/nuclearkatie/cyclus/cycamore/src/sink.h:9,
                 from /home/nuclearkatie/cyclus/cycamore/src/sink.cc:7:
/home/nuclearkatie/.local/include/cyclus/toolkit/res_buf.h:282:7: error: no matching function for call to ‘cyclus::Resource::ChangePackageId()’
  282 |       m->ChangePackageId();
      |       ^
In file included from /home/nuclearkatie/.local/include/cyclus/agent.h:15,
                 from /home/nuclearkatie/.local/include/cyclus/context.h:17,
                 from /home/nuclearkatie/.local/include/cyclus/cyclus.h:11,
                 from /home/nuclearkatie/cyclus/cycamore/src/sink.h:9,
                 from /home/nuclearkatie/cyclus/cycamore/src/sink.cc:7:
/home/nuclearkatie/.local/include/cyclus/resource.h:98:16: note: candidate: ‘virtual void cyclus::Resource::ChangePackageId(int)’
   98 |   virtual void ChangePackageId(int new_package_id) = 0;
      |                ^~~~~~~~~~~~~~~

**Comment by gonuke** [comment]
Just pushed a change that will hopefully fix it - but haven't tried myself

**Comment by nuclearkatie** [comment]
nope, same errors

**Comment by gonuke** [comment]
The newest change works for me now - actually tested locally!

**Comment by nuclearkatie** [comment]
Thanks @gonuke !

**Pull request merged**
